services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: ${TARGET:-development}
    ports:
      - "5173:5173"
    depends_on:
      - server
    env_file:
      - ./web/.env
    volumes:
      - ./web:/app
      - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${TARGET:-development}
    ports:
      - "3030:3030"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
